### ISSUE TITLE
an error description about Telegram ?

### ISSUE THREAD

**Issue by cmmei** [veekaybee/veekaybee.github.io#13]
https://veekaybee.github.io/2017/02/01/facebook-is-collecting-this/ 

On the [last head](https://github.com/veekaybee/veekaybee.github.io/blob/master/_posts/2017-02-01-facebook-is-collecting-this.md#what-should-i-do-if-i-dont-want-facebook-to-have-my-data) of the article, maybe there is an error description about Telegram:

> 5. Don't use Facebook, particularly Messenger to organize or attend political events. If you need to organize, use Facebook as a starting point, and then get on another platform. Recommended Platforms: Signal is the gold standard for private chat right now. Whatsapp is ok for group chat, but, I don't recommend because it's tied to Facebook's system of metadata. Telegram is also good, but not as good because it's closed source. Again, it depends on your level of risk. Here is more on these platforms.

Telegram's source code is in [its website](https://telegram.org/apps#source-code).

**Comment by veekaybee** [comment]
Agree. That was misphrasing on my part. I should have clarified that while the code is open-source, there is some swirl about their [encryption scheme.](https://security.stackexchange.com/questions/49782/is-telegram-secure)
