### ISSUE TITLE
Chinese translation: what should you think about when using Facebook ?

### ISSUE THREAD

**Issue by cmmei** [veekaybee/veekaybee.github.io#14]
Here is my translation to [what should you think about when using facebook?](https://veekaybee.github.io/2017/02/01/facebook-is-collecting-this/)

Chinese translation : https://chenmei.xyz/post/what-should-you-think-about-when-using-facebook

If there is any incorrect, I would correct it.

**Comment by veekaybee** [comment]
Thank you so much for doing this! I've added the link to the main page.
