### ISSUE TITLE
Confused by __init__.py examples in 2017-09-26-python-packaging.md

### ISSUE THREAD

**Issue by mnmt** [veekaybee/veekaybee.github.io#6]
First, thank you for writing [this article ](http://veekaybee.github.io/2017/09/26/python-packaging/)😄 . I would also like to add before hand that I don't know that much about packaging, so this is just my own observation as a reader of the article, and could be just my own misunderstanding. I also don't at all expect you to explain the things I am confused about, it's my job to try do more research; I just wanted to give some feedback 😁.

Under the [Scripts section](https://github.com/veekaybee/veekaybee.github.io/blob/master/_posts/2017-09-26-python-packaging.md#scripts) and the [`__main__.py` driver section](https://github.com/veekaybee/veekaybee.github.io/blob/master/_posts/2017-09-26-python-packaging.md#__mainpy__-driver), the examples given were a little confusing for me concerning the `__init__.py`'s. Replicating the second of the two below:

```
 textedit - package
 	__init__.py
 	__main__.py
 	bin/
 	textedit - module
 		__init__.py
		├── edit
			├── replace.py
			├── spacing.py
		├── review
			__init__.py
			├── wordcount.py
			└── readability.py
		├── tests
			└── test_wordcount.py
	README.MD
	requirements.txt
```
I don't understand, from reading what your wrote, why the `__init__.py`'s are where they are. From your explanation, 

> And, finally and most importantly, the `__init__.py`, which we'll want to add to every directory where you have runable Python modules.
> 
> If you remember from the Python innards overview `__init__` is a special file that will make Python realize that you have a package working together instead of a [single file](https://docs.python.org/3/tutorial/modules.html#packages).

, I'd suspect that each directory would need one, since each directory has within it, or in a directory below it, python code that we want to have as runable modules. The fact that `review` has an `__init__.py` but `edit` (and to a lesser degree, `tests`) doesn't is particularly odd to me. I'm also not 100% sure, from reading what you wrote, if the "textedit - module" directory does in fact need one. 

This is also a little confusing because the current [code on github](https://github.com/veekaybee/textedit) has an `__init__.py` at the top package level, but not one at the level below, and does have one present within `tests` and `edit`. Trying to look up about this leads me (potentially mistakenly) to [namespace packages](https://packaging.python.org/guides/packaging-namespace-packages/) and [PEP-420](https://www.python.org/dev/peps/pep-0420/), which could be applicable but for now is a bit beyond what I can understand.

If you can explain this a bit to me that would be appreciated, but I mainly wanted to let you know that the schematic directory tree examples mentioned seem a bit confusing, and the jump from them to the last schematic in the [Setup.py section](https://github.com/veekaybee/veekaybee.github.io/blob/master/_posts/2017-09-26-python-packaging.md#setuppy) isn't clear to me.

**Comment by veekaybee** [comment]
Thanks for commenting, @mnmt. In the code snippet that you quoted, I missed an __init__.py in the review and tests. The __init__.py file makes Python treats any given directory as if it has a module, so in theory you only need one at the top level, however, in practice, all directories and subdirectories of a project will have one (check out Django for an example.)
