### ISSUE TITLE
__init.py__ and __main.py__ are mostly used instead of __init__.py and __main__.py in 2017-09-26-python-packaging.md 

### ISSUE THREAD

**Issue by mnmt** [veekaybee/veekaybee.github.io#7]
As stated in the title, [this article](https://github.com/veekaybee/veekaybee.github.io/blob/master/_posts/2017-09-26-python-packaging.md) seems to erroneously use \_\_init.py\_\_ and \_\_main.py\_\_ quite a lot. 

Searching for `.py__`, this occurs in the section titles of \_\_init\_\_ and \_\_main\_\_, their respective entries in the contents page, once in the \_\_main\_\_ section, and once in the intro section.

Example:
![image](https://user-images.githubusercontent.com/4514181/31057819-b697dc82-a6e0-11e7-8e34-205c66b35f02.png)

**Comment by veekaybee** [comment]
@mnmt This should be fixed now, thanks!
